import {
  BaggyJeansDarkDenimGrey1,
  BaggyJeansDarkDenimGrey2,
  BaggyJeansPaleDenimBlue1,
  BaggyJeansPaleDenimBlue2,
  BaggyJeansPaleDenimBlue3,
  EmbroideredRigidSlimJeans1,
  EmbroideredRigidSlimJeans2,
  EmbroideredRigidSlimJeans3,
  LooseCargoJeansLightDenimBlue1,
  LooseCargoJeansLightDenimBlue2,
  LooseCargoJeansLightDenimBlue3,
  LooseJeansDarkDenimBlue1,
  LooseJeansDarkDenimBlue2,
  LooseJeansDarkDenimBlue3,
  RegularJeansDarkDenimGrey1,
  RegularJeansDarkDenimGrey2,
  RegularJeansDarkDenimGrey3,
  RegularJeansLightDenimBlue1,
  RegularJeansLightDenimBlue2,
  RegularJeansLightDenimBlue3,
  RegularTaperedJeansLightDenim1,
  RegularTaperedJeansLightDenim2,
  RegularTaperedJeansLightDenim3,
  RelaxedJeansBlack1,
  RelaxedJeansBlack2,
  RelaxedJeansBlack3,
  RigidSlimFitJeans1,
  RigidSlimFitJeans2,
  RigidSlimFitJeans3,
  RigidSlimFitJeans4,
  SlimCroppedJeans1,
  SlimCroppedJeans2,
  SlimCroppedJeans3,
  StraightRegularJeans1,
  StraightRegularJeans2,
  StraightRegularJeans3,
  StraightRegularJeans4,
  LooseFitTShirtWhite1,
  LooseFitTShirtWhite2,
  LooseFitTShirtWhite3,
  MenTBrown1,
  MenTBrown2,
  MenTBrown3,
  MenTDarkBrown1,
  MenTDarkBrown2,
  MenTDarkBrown3,
  RegularFitCorduroyShirtBurgundy1,
  RegularFitCorduroyShirtBurgundy2,
  RegularFitCorduroyShirtBurgundy3,
  RegularFitCorduroyShirtBurgundy4,
  RegularFitFeltedOvershirtNavyBlue1,
  RegularFitFeltedOvershirtNavyBlue2,
  RegularFitFeltedOvershirtNavyBlue3,
  RegularFitFeltedOvershirtNavyBlue4,
  RegularFitFeltedOvershirtWhite1,
  RegularFitFeltedOvershirtWhite2,
  RegularFitTexturedPoloShirtBlack1,
  RegularFitTexturedPoloShirtBlack2,
  RegularFitTexturedPoloShirtBlack3,
  ShirtsForMenCasualSmartShirtBlack1,
  ShirtsForMenCasualSmartShirtBlack2,
  ShirtsForMenCasualSmartShirtBlack3,
  ShirtsForMenCasualSmartShirtBlack4,
  ShirtsForMenCasualSmartShirtGrey1,
  ShirtsForMenCasualSmartShirtGrey2,
  ShirtsForMenCasualSmartShirtGrey3,
  ShirtsForMenCasualSmartShirtGrey4,
  ShirtsForMenCasualSmartShirtNavyBlue1,
  ShirtsForMenCasualSmartShirtNavyBlue2,
  ShirtsForMenCasualSmartShirtNavyBlue3,
  SlimFitEasyIronShirtBlack1,
  SlimFitEasyIronShirtBlack2,
  SlimFitEasyIronShirtBlack3,
  SlimFitPoloShirtBlack1,
  SlimFitPoloShirtBlack2,
  SlimFitPoloShirtBlack3,
  SlimFitPoloShirtDarkTurquoise1,
  SlimFitPoloShirtDarkTurquoise2,
  SlimFitPoloShirtDarkTurquoise3,
  SlimFitPoloShirtForestGreen1,
  SlimFitPoloShirtForestGreen2,
  SlimFitPoloShirtForestGreen3,
  SlimFitPoloShirtNavyBlue1,
  SlimFitPoloShirtNavyBlue2,
  SlimFitPoloShirtNavyBlue3,
} from "../../public/men.js";

export const menCategories = {
  jeans: [
    {
      imagePath: [BaggyJeansDarkDenimGrey1, BaggyJeansDarkDenimGrey2],
      title: "Baggy Jeans",
      subtitle: "Baggy Fit",
      description:
        "Comfortable and stylish baggy jeans in dark denim grey, perfect for a relaxed look.",
      price: "$18.99",
      gender: "Men",
      colors: ["#333333"],
    },
    {
      imagePath: [
        BaggyJeansPaleDenimBlue1,
        BaggyJeansPaleDenimBlue2,
        BaggyJeansPaleDenimBlue3,
      ],
      title: "Baggy Jeans",
      subtitle: "Baggy Fit",
      description:
        "Trendy baggy jeans in pale denim blue, ideal for a casual and modern style.",
      price: "$17.49",
      gender: "Men",
      colors: ["#778FA8"],
    },
    {
      imagePath: [
        EmbroideredRigidSlimJeans1,
        EmbroideredRigidSlimJeans2,
        EmbroideredRigidSlimJeans3,
      ],
      title: "Embroidered Rigid Slim Jeans",
      subtitle: "Slim Fit",
      description:
        "Stylish embroidered rigid slim jeans, perfect for a unique and fashionable look.",
      price: "$19.99",
      gender: "Men",
      colors: ["black"],
    },
    {
      imagePath: [
        LooseCargoJeansLightDenimBlue1,
        LooseCargoJeansLightDenimBlue2,
        LooseCargoJeansLightDenimBlue3,
      ],
      title: "Loose Cargo Jeans",
      subtitle: "Loose Fit",
      description:
        "Comfortable loose cargo jeans in light denim blue, great for a casual and functional style.",
      price: "$16.99",
      gender: "Men",
      colors: ["#6F8FAF"],
    },
    {
      imagePath: [
        LooseJeansDarkDenimBlue1,
        LooseJeansDarkDenimBlue2,
        LooseJeansDarkDenimBlue3,
      ],
      title: "Loose Jeans",
      subtitle: "Loose Fit",
      description:
        "Relaxed fit loose jeans in dark denim blue, perfect for a laid-back and stylish look.",
      price: "$18.49",
      gender: "Men",
      colors: ["#1B3F8B"],
    },
    {
      imagePath: [
        RegularJeansDarkDenimGrey1,
        RegularJeansDarkDenimGrey2,
        RegularJeansDarkDenimGrey3,
      ],
      title: "Regular Jeans",
      subtitle: "Regular Fit",
      description:
        "Classic regular jeans in dark denim grey, ideal for a timeless and versatile style.",
      price: "$17.99",
      gender: "Men",
      colors: ["#2F2F2F"],
    },
    {
      imagePath: [
        RegularJeansLightDenimBlue1,
        RegularJeansLightDenimBlue2,
        RegularJeansLightDenimBlue3,
      ],
      title: "Regular Jeans",
      subtitle: "Regular Fit",
      description:
        "Classic regular jeans in light denim blue, perfect for a fresh and casual look.",
      price: "$18.49",
      gender: "Men",
      colors: ["#6F8FAF"],
    },
    {
      imagePath: [
        RegularTaperedJeansLightDenim1,
        RegularTaperedJeansLightDenim2,
        RegularTaperedJeansLightDenim3,
      ],
      title: "Regular Tapered Jeans",
      subtitle: "Tapered Fit",
      description:
        "Stylish regular tapered jeans in light denim, great for a modern and sleek style.",
      price: "$19.49",
      gender: "Men",
      colors: ["#4F7CAC"],
    },
    {
      imagePath: [RelaxedJeansBlack1, RelaxedJeansBlack2, RelaxedJeansBlack3],
      title: "Relaxed Jeans",
      subtitle: "Relaxed Fit",
      description:
        "Comfortable relaxed jeans in black, perfect for a casual and versatile look.",
      price: "$17.49",
      gender: "Men",
      colors: ["Black"],
    },
    {
      imagePath: [
        RigidSlimFitJeans1,
        RigidSlimFitJeans2,
        RigidSlimFitJeans3,
        RigidSlimFitJeans4,
      ],
      title: "Rigid Slim Fit Jeans",
      subtitle: "Slim Fit",
      description:
        "Stylish rigid slim fit jeans, ideal for a sleek and modern look.",
      price: "$18.99",
      gender: "Men",
      colors: ["#333333"],
    },
    {
      imagePath: [SlimCroppedJeans1, SlimCroppedJeans2, SlimCroppedJeans3],
      title: "Slim Cropped Jeans",
      subtitle: "Slim Fit",
      description:
        "Trendy slim cropped jeans, perfect for a fashionable and contemporary style.",
      price: "$19.49",
      gender: "Men",
      colors: ["#1B3F8B"],
    },
    {
      imagePath: [
        StraightRegularJeans1,
        StraightRegularJeans2,
        StraightRegularJeans3,
        StraightRegularJeans4,
      ],
      title: "Straight Regular Jeans",
      subtitle: "Regular Fit",
      description:
        "Classic straight regular jeans, ideal for a timeless and versatile look.",
      price: "$18.49",
      gender: "Men",
      colors: ["black"],
    },
  ],
  shirts: [
    {
      imagePath: [
        LooseFitTShirtWhite1,
        LooseFitTShirtWhite2,
        LooseFitTShirtWhite3,
      ],
      title: "Loose Fit T-Shirt",
      subtitle: "Loose Fit",
      description:
        "Comfortable loose fit t-shirt in white, perfect for a casual and relaxed style.",
      price: "$15.99",
      gender: "Men",
      colors: ["darkolivegreen"],
    },
    {
      imagePath: [MenTBrown1, MenTBrown2, MenTBrown3],
      title: "Men T-Shirt",
      subtitle: "Regular Fit",
      description:
        "Stylish men t-shirt in brown, great for a casual and modern look.",
      price: "$16.49",
      gender: "Men",
      colors: ["Brown"],
    },
    {
      imagePath: [MenTDarkBrown1, MenTDarkBrown2, MenTDarkBrown3],
      title: "Men T-Shirt",
      subtitle: "Regular Fit",
      description:
        "Trendy men t-shirt in dark brown, perfect for a sleek and contemporary style.",
      price: "$16.99",
      gender: "Men",
      colors: ["saddlebrown"],
    },
    {
      imagePath: [
        RegularFitCorduroyShirtBurgundy1,
        RegularFitCorduroyShirtBurgundy2,
        RegularFitCorduroyShirtBurgundy3,
        RegularFitCorduroyShirtBurgundy4,
      ],
      title: "Regular Fit Corduroy Shirt",
      subtitle: "Regular Fit",
      description:
        "Stylish regular fit corduroy shirt in burgundy, perfect for a sophisticated and modern look.",
      price: "$18.99",
      gender: "Men",
      colors: ["maroon"],
    },
    {
      imagePath: [
        RegularFitFeltedOvershirtNavyBlue1,
        RegularFitFeltedOvershirtNavyBlue2,
        RegularFitFeltedOvershirtNavyBlue3,
        RegularFitFeltedOvershirtNavyBlue4,
      ],
      title: "Regular Fit Felted Overshirt",
      subtitle: "Regular Fit",
      description:
        "Comfortable regular fit felted overshirt in navy blue, great for a casual and stylish look.",
      price: "$19.49",
      gender: "Men",
      colors: ["navy"],
    },
    {
      imagePath: [
        RegularFitFeltedOvershirtWhite1,
        RegularFitFeltedOvershirtWhite2,
      ],
      title: "Regular Fit Felted Overshirt",
      subtitle: "Regular Fit",
      description:
        "Classic regular fit felted overshirt in white, perfect for a fresh and versatile style.",
      price: "$18.99",
      gender: "Men",
      colors: ["White"],
    },
    {
      imagePath: [
        RegularFitTexturedPoloShirtBlack1,
        RegularFitTexturedPoloShirtBlack2,
        RegularFitTexturedPoloShirtBlack3,
      ],
      title: "Regular Fit Textured Polo Shirt",
      subtitle: "Regular Fit",
      description:
        "Stylish regular fit textured polo shirt in black, great for a sleek and modern look.",
      price: "$17.49",
      gender: "Men",
      colors: ["Black"],
    },
    {
      imagePath: [
        ShirtsForMenCasualSmartShirtBlack1,
        ShirtsForMenCasualSmartShirtBlack2,
        ShirtsForMenCasualSmartShirtBlack3,
        ShirtsForMenCasualSmartShirtBlack4,
      ],
      title: "Casual Smart Shirt",
      subtitle: "Regular Fit",
      description:
        "Elegant casual smart shirt in black, perfect for a versatile and polished look.",
      price: "$19.49",
      gender: "Men",
      colors: ["Black"],
    },
    {
      imagePath: [
        ShirtsForMenCasualSmartShirtGrey1,
        ShirtsForMenCasualSmartShirtGrey2,
        ShirtsForMenCasualSmartShirtGrey3,
        ShirtsForMenCasualSmartShirtGrey4,
      ],
      title: "Casual Smart Shirt",
      subtitle: "Regular Fit",
      description:
        "Sophisticated casual smart shirt in grey, ideal for a modern and stylish look.",
      price: "$18.99",
      gender: "Men",
      colors: ["Grey"],
    },
    {
      imagePath: [
        ShirtsForMenCasualSmartShirtNavyBlue1,
        ShirtsForMenCasualSmartShirtNavyBlue2,
        ShirtsForMenCasualSmartShirtNavyBlue3,
      ],
      title: "Casual Smart Shirt",
      subtitle: "Regular Fit",
      description:
        "Stylish casual smart shirt in navy blue, perfect for a versatile and modern look.",
      price: "$19.49",
      gender: "Men",
      colors: ["lightblue"],
    },
    {
      imagePath: [
        SlimFitEasyIronShirtBlack1,
        SlimFitEasyIronShirtBlack2,
        SlimFitEasyIronShirtBlack3,
      ],
      title: "Slim Fit Easy-Iron Shirt",
      subtitle: "Slim Fit",
      description:
        "Convenient slim fit easy-iron shirt in black, perfect for a sleek and polished look.",
      price: "$17.49",
      gender: "Men",
      colors: ["Black"],
    },
    {
      imagePath: [
        SlimFitPoloShirtBlack1,
        SlimFitPoloShirtBlack2,
        SlimFitPoloShirtBlack3,
      ],
      title: "Slim Fit Polo Shirt",
      subtitle: "Slim Fit",
      description:
        "Stylish slim fit polo shirt in black, great for a modern and sleek look.",
      price: "$16.99",
      gender: "Men",
      colors: ["Black"],
    },
    {
      imagePath: [
        SlimFitPoloShirtDarkTurquoise1,
        SlimFitPoloShirtDarkTurquoise2,
        SlimFitPoloShirtDarkTurquoise3,
      ],
      title: "Slim Fit Polo Shirt",
      subtitle: "Slim Fit",
      description:
        "Trendy slim fit polo shirt in dark turquoise, perfect for a trendy and stylish look.",
      price: "$17.49",
      gender: "Men",
      colors: ["DarkTurquoise"],
    },
    {
      imagePath: [
        SlimFitPoloShirtForestGreen1,
        SlimFitPoloShirtForestGreen2,
        SlimFitPoloShirtForestGreen3,
      ],
      title: "Slim Fit Polo Shirt",
      subtitle: "Slim Fit",
      description:
        "Stylish slim fit polo shirt in forest green, great for a modern and sleek look.",
      price: "$16.99",
      gender: "Men",
      colors: ["ForestGreen"],
    },
    {
      imagePath: [
        SlimFitPoloShirtNavyBlue1,
        SlimFitPoloShirtNavyBlue2,
        SlimFitPoloShirtNavyBlue3,
      ],
      title: "Slim Fit Polo Shirt",
      subtitle: "Slim Fit",
      description:
        "Stylish slim fit polo shirt in navy blue, perfect for a versatile and modern look.",
      price: "$17.49",
      gender: "Men",
      colors: ["Navy"],
    },
  ],
};
