import {
  BasicPopoverShirtNavyBlue1,
  BasicPopoverShirtNavyBlue2,
  BasicPopoverShirtNavyBlue3,
  BasicPopoverShirtWhite1,
  BasicPopoverShirtWhite2,
  BasicPopoverShirtWhite3,
  LooseFitPrintedTShirt1,
  LooseFitPrintedTShirt2,
  LooseFitPrintedTShirt3,
  LooseFitPrintedTShirt4,
  LooseFitPrintedTShirt5,
  LooseFitPrintedTShirt6,
  LooseFitPrintedTShirt7,
  LooseFitShortSleevedShirt1,
  LooseFitShortSleevedShirt2,
  PatternedResortShirt1,
  PatternedResortShirt2,
  PatternedResortShirt3,
  PatternedResortShirt4,
  PatternedResortShirt5,
  PatternedResortShirt6,
  PatternedResortShirtBlack1,
  PatternedResortShirtBlack2,
  RegularFitHoodie1,
  RegularFitHoodie2,
  RegularFitHoodie3,
  RegularFitHoodie4,
  RegularFitHoodie5,
  RegularFitHoodie6,
  RegularFitHoodie7,
  RegularFitPrintedTShirt1,
  RegularFitPrintedTShirt2,
  RegularFitTShirt1,
  RegularFitTShirt2,
  RegularFitWaffledTShirt1,
  RegularFitWaffledTShirt2,
  SloganTShirtBlack1,
  SloganTShirtBlack2,
  SloganTShirtBrown1,
  SloganTShirtBrown2,
  SloganTShirtBrown3,
  StraightTrousers1,
  StraightTrousers2,
  // Women
  BasicBasicTShirt1,
  BasicBasicTShirt2,
  BasicBasicTShirt3,
  BasicBasicTShirt4,
  BasicBasicTShirt5,
  BasicBasicTShirt6,
  BasicOversizedTShirt1,
  BasicOversizedTShirt2,
  CableKnitCroppedCardiganNavyBlue,
  CableKnitCroppedCardiganWhite,
  CrewNeckStripedCroppedSweater1,
  CrewNeckStripedCroppedSweater2,
  CrewNeckStripedCroppedSweater3,
  CroppedBasicPlushSweaterBeige1,
  CroppedBasicPlushSweaterBeige2,
  CroppedBasicPlushSweaterBeige3,
  CroppedBasicPlushSweaterNavyBlue1,
  CroppedBasicPlushSweaterNavyBlue2,
  CroppedBasicPlushSweaterNavyBlue3,
  CroppedBasicPlushSweaterNavyBlue4,
  CroppedSuedeBomberJacket1,
  CroppedSuedeBomberJacket2,
  CroppedSuedeBomberJacket3,
  EmbellishedCrewNeckSweatshirt1,
  EmbellishedCrewNeckSweatshirt2,
  HighRiseSkinnyJeans1,
  HighRiseSkinnyJeans2,
  HighRiseSkinnyJeans3,
  HighRiseSkinnyJeans4,
  HighRiseSkinnyPants1,
  HighRiseSkinnyPants2,
  HighRiseSkinnyPants3,
  PoloCollarSweatshirtWithEmbellishment1,
  PoloCollarSweatshirtWithEmbellishment2,
  PoloCollarSweatshirtWithEmbellishment3,
  PoloCollarSweatshirtWithEmbellishment4,
  StripedSweater1,
  StripedSweater2,
  StripedSweater3,
  SuperCroppedEmbellishedTShirt1,
  SuperCroppedEmbellishedTShirt2,
  SuperCroppedEmbellishedTShirt3,
  SuperCroppedVNeckShirtWithKnottedHem1,
  SuperCroppedVNeckShirtWithKnottedHem2,
  SuperCroppedVNeckShirtWithKnottedHem3,
} from "../../public/sales.js";

export const saleCategories = {
  Men: [
    {
      imagePath: [BasicPopoverShirtNavyBlue1, BasicPopoverShirtNavyBlue2, BasicPopoverShirtNavyBlue3],
      title: 'Basic Popover Shirt',
      subtitle: 'Regular Fit',
      description: 'Classic basic popover shirt in navy blue, perfect for a casual and stylish look.',
      price: '$15.99',
      discountedPrice: '$13.99',
      discountPercentage: '13%',
      gender: 'Men',
      colors: ['Navy Blue'],
    },
    {
      imagePath: [BasicPopoverShirtWhite1, BasicPopoverShirtWhite2, BasicPopoverShirtWhite3],
      title: 'Basic Popover Shirt',
      subtitle: 'Regular Fit',
      description: 'Classic basic popover shirt in white, perfect for a casual and stylish look.',
      price: '$15.99',
      discountedPrice: '$13.99',
      discountPercentage: '13%',
      gender: 'Men',
      colors: ['White'],
    },
    {
      imagePath: [LooseFitPrintedTShirt1, LooseFitPrintedTShirt2, LooseFitPrintedTShirt3, LooseFitPrintedTShirt4, LooseFitPrintedTShirt5, LooseFitPrintedTShirt6, LooseFitPrintedTShirt7],
      title: 'Loose Fit Printed T-Shirt',
      subtitle: 'Loose Fit',
      description: 'Comfortable loose fit printed t-shirt, perfect for a casual and relaxed style.',
      price: '$12.99',
      discountedPrice: '$10.99',
      discountPercentage: '15%',
      gender: 'Men',
      colors: ['Various'],
    },
    {
      imagePath: [LooseFitShortSleevedShirt1, LooseFitShortSleevedShirt2],
      title: 'Loose Fit Short Sleeved Shirt',
      subtitle: 'Loose Fit',
      description: 'Comfortable loose fit short sleeved shirt, perfect for a casual and relaxed style.',
      price: '$14.99',
      discountedPrice: '$11.99',
      discountPercentage: '20%',
      gender: 'Men',
      colors: ['Various'],
    },
    {
      imagePath: [PatternedResortShirt1, PatternedResortShirt2, PatternedResortShirt3, PatternedResortShirt4, PatternedResortShirt5, PatternedResortShirt6],
      title: 'Patterned Resort Shirt',
      subtitle: 'Regular Fit',
      description: 'Stylish patterned resort shirt, perfect for a fashionable and relaxed look.',
      price: '$16.99',
      discountedPrice: '$13.99',
      discountPercentage: '18%',
      gender: 'Men',
      colors: ['Various'],
    },
    {
      imagePath: [PatternedResortShirtBlack1, PatternedResortShirtBlack2],
      title: 'Patterned Resort Shirt',
      subtitle: 'Regular Fit',
      description: 'Stylish patterned resort shirt in black, perfect for a fashionable and relaxed look.',
      price: '$16.99',
      discountedPrice: '$13.99',
      discountPercentage: '18%',
      gender: 'Men',
      colors: ['Black'],
    },
    {
      imagePath: [RegularFitHoodie1, RegularFitHoodie2, RegularFitHoodie3, RegularFitHoodie4, RegularFitHoodie5, RegularFitHoodie6, RegularFitHoodie7],
      title: 'Regular Fit Hoodie',
      subtitle: 'Regular Fit',
      description: 'Comfortable regular fit hoodie, perfect for a casual and relaxed style.',
      price: '$19.99',
      discountedPrice: '$15.99',
      discountPercentage: '20%',
      gender: 'Men',
      colors: ['Various'],
    },
    {
      imagePath: [RegularFitPrintedTShirt1, RegularFitPrintedTShirt2],
      title: 'Regular Fit Printed T-Shirt',
      subtitle: 'Regular Fit',
      description: 'Comfortable regular fit printed t-shirt, perfect for a casual and relaxed style.',
      price: '$12.99',
      discountedPrice: '$10.99',
      discountPercentage: '15%',
      gender: 'Men',
      colors: ['Various'],
    },
    {
      imagePath: [RegularFitTShirt1, RegularFitTShirt2],
      title: 'Regular Fit T-Shirt',
      subtitle: 'Regular Fit',
      description: 'Comfortable regular fit t-shirt, perfect for a casual and relaxed style.',
      price: '$11.99',
      discountedPrice: '$9.99',
      discountPercentage: '17%',
      gender: 'Men',
      colors: ['Various'],
    },
    {
      imagePath: [RegularFitWaffledTShirt1, RegularFitWaffledTShirt2],
      title: 'Regular Fit Waffled T-Shirt',
      subtitle: 'Regular Fit',
      description: 'Comfortable regular fit waffled t-shirt, perfect for a casual and relaxed style.',
      price: '$13.99',
      discountedPrice: '$11.99',
      discountPercentage: '14%',
      gender: 'Men',
      colors: ['Various'],
    },
    {
      imagePath: [SloganTShirtBlack1, SloganTShirtBlack2],
      title: 'Slogan T-Shirt',
      subtitle: 'Regular Fit',
      description: 'Stylish slogan t-shirt in black, perfect for a casual and modern look.',
      price: '$14.99',
      discountedPrice: '$11.99',
      discountPercentage: '20%',
      gender: 'Men',
      colors: ['Black'],
    },
    {
      imagePath: [SloganTShirtBrown1, SloganTShirtBrown2, SloganTShirtBrown3],
      title: 'Slogan T-Shirt',
      subtitle: 'Regular Fit',
      description: 'Stylish slogan t-shirt in brown, perfect for a casual and modern look.',
      price: '$14.99',
      discountedPrice: '$11.99',
      discountPercentage: '20%',
      gender: 'Men',
      colors: ['Brown'],
    },
    {
      imagePath: [StraightTrousers1, StraightTrousers2],
      title: 'Straight Trousers',
      subtitle: 'Regular Fit',
      description: 'Classic straight trousers, perfect for a timeless and versatile look.',
      price: '$19.99',
      discountedPrice: '$15.99',
      discountPercentage: '20%',
      gender: 'Men',
      colors: ['Various'],
    },
  ],
  Women: [
    {
      imagePath: [BasicBasicTShirt1, BasicBasicTShirt2, BasicBasicTShirt3, BasicBasicTShirt4, BasicBasicTShirt5, BasicBasicTShirt6],
      title: 'Basic T-Shirt',
      subtitle: 'Regular Fit',
      description: 'Comfortable basic t-shirt, perfect for a casual and relaxed style.',
      price: '$9.99',
      discountedPrice: '$8.49',
      discountPercentage: '15%',
      gender: 'Women',
      colors: ['Various'],
    },
    {
      imagePath: [BasicOversizedTShirt1, BasicOversizedTShirt2],
      title: 'Basic Oversized T-Shirt',
      subtitle: 'Oversized Fit',
      description: 'Comfortable basic oversized t-shirt, perfect for a casual and relaxed style.',
      price: '$11.99',
      discountedPrice: '$9.99',
      discountPercentage: '17%',
      gender: 'Women',
      colors: ['Various'],
    },
    {
      imagePath: [CableKnitCroppedCardiganNavyBlue, CableKnitCroppedCardiganWhite],
      title: 'Cable Knit Cropped Cardigan',
      subtitle: 'Regular Fit',
      description: 'Stylish cable knit cropped cardigan, perfect for a fashionable and cozy look.',
      price: '$19.99',
      discountedPrice: '$15.99',
      discountPercentage: '20%',
      gender: 'Women',
      colors: ['Navy Blue', 'White'],
    },
    {
      imagePath: [CrewNeckStripedCroppedSweater1, CrewNeckStripedCroppedSweater2, CrewNeckStripedCroppedSweater3],
      title: 'Crew Neck Striped Cropped Sweater',
      subtitle: 'Regular Fit',
      description: 'Stylish crew neck striped cropped sweater, perfect for a fashionable and cozy look.',
      price: '$18.99',
      discountedPrice: '$14.99',
      discountPercentage: '21%',
      gender: 'Women',
      colors: ['Various'],
    },
    {
      imagePath: [CroppedBasicPlushSweaterBeige1, CroppedBasicPlushSweaterBeige2, CroppedBasicPlushSweaterBeige3],
      title: 'Cropped Basic Plush Sweater',
      subtitle: 'Regular Fit',
      description: 'Comfortable cropped basic plush sweater in beige, perfect for a cozy and stylish look.',
      price: '$17.99',
      discountedPrice: '$13.99',
      discountPercentage: '22%',
      gender: 'Women',
      colors: ['Beige'],
    },
    {
      imagePath: [CroppedBasicPlushSweaterNavyBlue1, CroppedBasicPlushSweaterNavyBlue2, CroppedBasicPlushSweaterNavyBlue3, CroppedBasicPlushSweaterNavyBlue4],
      title: 'Cropped Basic Plush Sweater',
      subtitle: 'Regular Fit',
      description: 'Comfortable cropped basic plush sweater in navy blue, perfect for a cozy and stylish look.',
      price: '$17.99',
      discountedPrice: '$13.99',
      discountPercentage: '22%',
      gender: 'Women',
      colors: ['Navy Blue'],
    },
    {
      imagePath: [CroppedSuedeBomberJacket1, CroppedSuedeBomberJacket2, CroppedSuedeBomberJacket3],
      title: 'Cropped Suede Bomber Jacket',
      subtitle: 'Regular Fit',
      description: 'Stylish cropped suede bomber jacket, perfect for a fashionable and modern look.',
      price: '$29.99',
      discountedPrice: '$23.99',
      discountPercentage: '20%',
      gender: 'Women',
      colors: ['Various'],
    },
    {
      imagePath: [EmbellishedCrewNeckSweatshirt1, EmbellishedCrewNeckSweatshirt2],
      title: 'Embellished Crew Neck Sweatshirt',
      subtitle: 'Regular Fit',
      description: 'Stylish embellished crew neck sweatshirt, perfect for a fashionable and cozy look.',
      price: '$19.99',
      discountedPrice: '$15.99',
      discountPercentage: '20%',
      gender: 'Women',
      colors: ['Various'],
    },
    {
      imagePath: [HighRiseSkinnyJeans1, HighRiseSkinnyJeans2, HighRiseSkinnyJeans3, HighRiseSkinnyJeans4],
      title: 'High Rise Skinny Jeans',
      subtitle: 'Skinny Fit',
      description: 'Stylish high rise skinny jeans, perfect for a fashionable and modern look.',
      price: '$24.99',
      discountedPrice: '$19.99',
      discountPercentage: '20%',
      gender: 'Women',
      colors: ['Various'],
    },
    {
      imagePath: [HighRiseSkinnyPants1, HighRiseSkinnyPants2, HighRiseSkinnyPants3],
      title: 'High Rise Skinny Pants',
      subtitle: 'Skinny Fit',
      description: 'Stylish high rise skinny pants, perfect for a fashionable and modern look.',
      price: '$22.99',
      discountedPrice: '$17.99',
      discountPercentage: '22%',
      gender: 'Women',
      colors: ['Various'],
    },
    {
      imagePath: [PoloCollarSweatshirtWithEmbellishment1, PoloCollarSweatshirtWithEmbellishment2, PoloCollarSweatshirtWithEmbellishment3, PoloCollarSweatshirtWithEmbellishment4],
      title: 'Polo Collar Sweatshirt with Embellishment',
      subtitle: 'Regular Fit',
      description: 'Stylish polo collar sweatshirt with embellishment, perfect for a fashionable and cozy look.',
      price: '$21.99',
      discountedPrice: '$16.99',
      discountPercentage: '23%',
      gender: 'Women',
      colors: ['Various'],
    },
    {
      imagePath: [StripedSweater1, StripedSweater2, StripedSweater3],
      title: 'Striped Sweater',
      subtitle: 'Regular Fit',
      description: 'Stylish striped sweater, perfect for a fashionable and cozy look.',
      price: '$19.99',
      discountedPrice: '$15.99',
      discountPercentage: '20%',
      gender: 'Women',
      colors: ['Various'],
    },
    {
      imagePath: [SuperCroppedEmbellishedTShirt1, SuperCroppedEmbellishedTShirt2, SuperCroppedEmbellishedTShirt3],
      title: 'Super Cropped Embellished T-Shirt',
      subtitle: 'Cropped Fit',
      description: 'Stylish super cropped embellished t-shirt, perfect for a fashionable and modern look.',
      price: '$14.99',
      discountedPrice: '$11.99',
      discountPercentage: '20%',
      gender: 'Women',
      colors: ['Various'],
    },
    {
      imagePath: [SuperCroppedVNeckShirtWithKnottedHem1, SuperCroppedVNeckShirtWithKnottedHem2, SuperCroppedVNeckShirtWithKnottedHem3],
      title: 'Super Cropped V-Neck Shirt with Knotted Hem',
      subtitle: 'Cropped Fit',
      description: 'Stylish super cropped v-neck shirt with knotted hem, perfect for a fashionable and modern look.',
      price: '$14.99',
      discountedPrice: '$11.99',
      discountPercentage: '20%',
      gender: 'Women',
      colors: ['Various'],
    },
  ],
};
