import {
  BaggyBoyFriendJeans1,
  BaggyBoyFriendJeans2,
  BaggyBoyFriendJeans3,
  BaggyBoyFriendJeans4,
  BasicMomFitJeans1,
  BasicMomFitJeans2,
  BasicMomFitJeans3,
  EmbroideredStraightFitJeans1,
  EmbroideredStraightFitJeans2,
  HighRiseSkinnyJeans1,
  HighRiseSkinnyJeans2,
  HighRiseSkinnyJeans3,
  PleatedCarrotFitTrousers1,
  SlimHighJeans1,
  SlimHighJeans2,
  SlimHighJeans3,
  SlimStraightHighJeans1,
  SlimStraightHighJeans2,
  StraightJeans1,
  StraightJeans2,
  StraightJeans3,
  WideLegTrousersWithSidePipping1,
  WideLegTrousersWithSidePipping2,
  WideBeltedJeansLightDenimBlue1,
  WideBeltedJeansLightDenimBlue2,
  WideBeltedJeansLightDenimBlue3,
  WideBeltedJeansLightDenimBlue4,
  WideBeltedJeansLightDenimWhite1,
  WideBeltedJeansLightDenimWhite2,
  WideBeltedJeansLightDenimWhite3,
  WideBeltedJeansLightDenimWhite4,
  WideJeans1,
  WideJeans2,
  WideJeans3,
  WideJeans4,
  BarrelHighBlack1,
  BarrelHighBlack2,
  BarrelHighBlack3,
  BarrelHighBlack4,
  BarrelHighBlue1,
  BarrelHighBlue2,
  BarrelHighBlue3,
  BarrelHighDarkBlue1,
  BarrelHighDarkBlue2,
  BandCollarBlouseNavyBlue1,
  BandCollarBlouseNavyBlue2,
  BandCollarBlouseNavyBlue3,
  BasicShacket1,
  BasicShacket2,
  BasicShacket3,
  FauxLeatherEmbroideredShirt1,
  FauxLeatherEmbroideredShirt2,
  FauxLeatherEmbroideredShirt3,
  FlounceTrimmedBlouse1,
  FlounceTrimmedBlouse2,
  FlounceTrimmedBlouse3,
  FlounceTrimmedBlouseCreamFloral1,
  FlounceTrimmedBlouseCreamFloral2,
  FlounceTrimmedBlouseCreamFloral3,
  LaceUpDenimShirtDenimBlue1,
  LaceUpDenimShirtDenimBlue2,
  LaceUpDenimShirtDenimBlue3,
  LinenShirtBlack1,
  LinenShirtBlack2,
  LinenShirtBlack3,
  LooseFitCottonShirt1,
  LooseFitCottonShirt2,
  LooseFitCottonShirt3,
  LyocellDenimShirt1,
  LyocellDenimShirt2,
  LyocellDenimShirt3,
  LyocellDenimShirt4,
  LyocellDenimShirtDenimBlue1,
  LyocellDenimShirtDenimBlue2,
  LyocellDenimShirtDenimBlue3,
  LyocellDenimShirtDenimGrey1,
  LyocellDenimShirtDenimGrey2,
  LyocellDenimShirtDenimGrey3,
  NonDenimShacket1,
  NonDenimShacket2,
  NonDenimShacket3,
  OxfordShirtLightPink1,
  OxfordShirtLightPink2,
  OxfordShirtLightPink3,
  PopoverDenimShirtCream1,
  PopoverDenimShirtCream2,
  PopoverDenimShirtCream3,
  SequinedBlouseDarkGrey1,
  SequinedBlouseDarkGrey2,
  SequinedBlouseDarkGrey3,
  WomensBlousesShirtsDenimSatinLinen1,
  WomensBlousesShirtsDenimSatinLinen2,
  WomensBlousesShirtsDenimSatinLinen3,
  WomensBlousesShirtsDenimSatinLinen4,
  CigaretteTrousersBlack1,
  CigaretteTrousersBlack2,
  CigaretteTrousersBlack3,
  FineKnitTrousersDarkBeige1,
  FineKnitTrousersDarkBeige2,
  FineKnitTrousersDarkBeige3,
  FlaredRibKnitTrousersBlack1,
  FlaredRibKnitTrousersBlack2,
  FlaredRibKnitTrousersBlack3,
  FlaredSportsLeggingsInDryMove1,
  FlaredSportsLeggingsInDryMove2,
  FlaredSportsLeggingsInDryMove3,
  HighWaistedLeggingsBlack1,
  HighWaistedLeggingsBlack2,
  HighWaistedLeggingsBlack3,
  SweatpantsBlack1,
  SweatpantsBlack2,
  SweatpantsBlack3,
  TailoredJerseyTrousersNavy1,
  TailoredJerseyTrousersNavy2,
  TailoredJerseyTrousersNavy3,
  TailoredJerseyTrousersNavy4,
  WideJoggersPigeonBlue1,
  WideJoggersPigeonBlue2,
  WideJoggersPigeonBlue3,
  WideTailoredTrousers1,
  WideTailoredTrousers2,
  WideTailoredTrousers3,
  WideTwillTrousersBlack1,
  WideTwillTrousersBlack2,
  WideTwillTrousersBlack3,
} from "../../public/women.js";

export const womenCategories = {
  jeans: [
    {
      imagePath: [
        BaggyBoyFriendJeans1,
        BaggyBoyFriendJeans2,
        BaggyBoyFriendJeans3,
        BaggyBoyFriendJeans4,
      ],
      title: "Baggy Boyfriend Jeans",
      subtitle: "Baggy Fit",
      description:
        "Comfortable and stylish baggy boyfriend jeans, perfect for a relaxed look.",
      price: "$19.99",
      gender: "Women",
      colors: ["Denim Blue"],
    },
    {
      imagePath: [BasicMomFitJeans1, BasicMomFitJeans2, BasicMomFitJeans3],
      title: "Basic Mom Fit Jeans",
      subtitle: "Mom Fit",
      description:
        "Trendy basic mom fit jeans, ideal for a casual and modern style.",
      price: "$18.49",
      gender: "Women",
      colors: ["Denim Blue"],
    },
    {
      imagePath: [EmbroideredStraightFitJeans1, EmbroideredStraightFitJeans2],
      title: "Embroidered Straight Fit Jeans",
      subtitle: "Straight Fit",
      description:
        "Stylish embroidered straight fit jeans, perfect for a unique and fashionable look.",
      price: "$20.99",
      gender: "Women",
      colors: ["Denim Blue"],
    },
    {
      imagePath: [
        HighRiseSkinnyJeans1,
        HighRiseSkinnyJeans2,
        HighRiseSkinnyJeans3,
      ],
      title: "High Rise Skinny Jeans",
      subtitle: "Skinny Fit",
      description:
        "Comfortable high rise skinny jeans, great for a sleek and modern style.",
      price: "$21.49",
      gender: "Women",
      colors: ["Denim Blue"],
    },
    {
      imagePath: [PleatedCarrotFitTrousers1],
      title: "Pleated Carrot Fit Trousers",
      subtitle: "Carrot Fit",
      description:
        "Elegant pleated carrot fit trousers, ideal for a sophisticated and stylish look.",
      price: "$22.99",
      gender: "Women",
      colors: ["Black"],
    },
    {
      imagePath: [SlimHighJeans1, SlimHighJeans2, SlimHighJeans3],
      title: "Slim High Jeans",
      subtitle: "Slim Fit",
      description:
        "Trendy slim high jeans, perfect for a fashionable and contemporary style.",
      price: "$19.99",
      gender: "Women",
      colors: ["Denim Blue"],
    },
    {
      imagePath: [SlimStraightHighJeans1, SlimStraightHighJeans2],
      title: "Slim Straight High Jeans",
      subtitle: "Slim Straight Fit",
      description:
        "Stylish slim straight high jeans, great for a modern and sleek look.",
      price: "$20.49",
      gender: "Women",
      colors: ["Denim Blue"],
    },
    {
      imagePath: [StraightJeans1, StraightJeans2, StraightJeans3],
      title: "Straight Jeans",
      subtitle: "Straight Fit",
      description:
        "Classic straight jeans, ideal for a timeless and versatile style.",
      price: "$18.99",
      gender: "Women",
      colors: ["Denim Blue"],
    },
    {
      imagePath: [
        WideLegTrousersWithSidePipping1,
        WideLegTrousersWithSidePipping2,
      ],
      title: "Wide Leg Trousers with Side Pipping",
      subtitle: "Wide Leg Fit",
      description:
        "Elegant wide leg trousers with side pipping, perfect for a sophisticated look.",
      price: "$23.49",
      gender: "Women",
      colors: ["Black"],
    },
    {
      imagePath: [
        WideBeltedJeansLightDenimBlue1,
        WideBeltedJeansLightDenimBlue2,
        WideBeltedJeansLightDenimBlue3,
        WideBeltedJeansLightDenimBlue4,
      ],
      title: "Wide Belted Jeans",
      subtitle: "Wide Fit",
      description:
        "Comfortable wide belted jeans, great for a relaxed and stylish look.",
      price: "$24.99",
      gender: "Women",
      colors: ["Light Denim Blue"],
    },
    {
      imagePath: [
        WideBeltedJeansLightDenimWhite1,
        WideBeltedJeansLightDenimWhite2,
        WideBeltedJeansLightDenimWhite3,
        WideBeltedJeansLightDenimWhite4,
      ],
      title: "Wide Belted Jeans",
      subtitle: "Wide Fit",
      description:
        "Comfortable wide belted jeans, great for a relaxed and stylish look.",
      price: "$24.99",
      gender: "Women",
      colors: ["Light Denim White"],
    },
    {
      imagePath: [WideJeans1, WideJeans2, WideJeans3, WideJeans4],
      title: "Wide Jeans",
      subtitle: "Wide Fit",
      description:
        "Comfortable wide jeans, perfect for a relaxed and stylish look.",
      price: "$22.49",
      gender: "Women",
      colors: ["Denim Blue"],
    },
  ],
  shirts: [
    {
      imagePath: [
        BandCollarBlouseNavyBlue1,
        BandCollarBlouseNavyBlue2,
        BandCollarBlouseNavyBlue3,
      ],
      title: "Band Collar Blouse",
      subtitle: "Regular Fit",
      description:
        "Elegant band collar blouse in navy blue, perfect for a sophisticated and modern look.",
      price: "$19.99",
      gender: "Women",
      colors: ["Navy Blue"],
    },
    {
      imagePath: [BasicShacket1, BasicShacket2, BasicShacket3],
      title: "Basic Shacket",
      subtitle: "Regular Fit",
      description:
        "Stylish basic shacket, great for a casual and modern style.",
      price: "$18.49",
      gender: "Women",
      colors: ["Denim Blue"],
    },
    {
      imagePath: [
        FauxLeatherEmbroideredShirt1,
        FauxLeatherEmbroideredShirt2,
        FauxLeatherEmbroideredShirt3,
      ],
      title: "Faux Leather Embroidered Shirt",
      subtitle: "Regular Fit",
      description:
        "Trendy faux leather embroidered shirt, perfect for a unique and fashionable look.",
      price: "$20.99",
      gender: "Women",
      colors: ["Black"],
    },
    {
      imagePath: [
        FlounceTrimmedBlouse1,
        FlounceTrimmedBlouse2,
        FlounceTrimmedBlouse3,
      ],
      title: "Flounce Trimmed Blouse",
      subtitle: "Regular Fit",
      description:
        "Elegant flounce trimmed blouse, great for a sophisticated and stylish look.",
      price: "$21.49",
      gender: "Women",
      colors: ["White"],
    },
    {
      imagePath: [
        LaceUpDenimShirtDenimBlue1,
        LaceUpDenimShirtDenimBlue2,
        LaceUpDenimShirtDenimBlue3,
      ],
      title: "Lace-Up Denim Shirt",
      subtitle: "Regular Fit",
      description:
        "Stylish lace-up denim shirt, ideal for a casual and modern style.",
      price: "$22.99",
      gender: "Women",
      colors: ["Denim Blue"],
    },
    {
      imagePath: [LinenShirtBlack1, LinenShirtBlack2, LinenShirtBlack3],
      title: "Linen Shirt",
      subtitle: "Regular Fit",
      description:
        "Comfortable linen shirt, perfect for a relaxed and stylish look.",
      price: "$19.99",
      gender: "Women",
      colors: ["Black"],
    },
    {
      imagePath: [
        LooseFitCottonShirt1,
        LooseFitCottonShirt2,
        LooseFitCottonShirt3,
      ],
      title: "Loose Fit Cotton Shirt",
      subtitle: "Loose Fit",
      description:
        "Comfortable loose fit cotton shirt, great for a casual and relaxed style.",
      price: "$18.49",
      gender: "Women",
      colors: ["White"],
    },
    {
      imagePath: [
        LyocellDenimShirt1,
        LyocellDenimShirt2,
        LyocellDenimShirt3,
        LyocellDenimShirt4,
      ],
      title: "Lyocell Denim Shirt",
      subtitle: "Regular Fit",
      description:
        "Stylish lyocell denim shirt, perfect for a modern and sleek look.",
      price: "$20.99",
      gender: "Women",
      colors: ["Denim Blue"],
    },
    {
      imagePath: [NonDenimShacket1, NonDenimShacket2, NonDenimShacket3],
      title: "Non-Denim Shacket",
      subtitle: "Regular Fit",
      description:
        "Trendy non-denim shacket, ideal for a fashionable and contemporary style.",
      price: "$21.49",
      gender: "Women",
      colors: ["Black"],
    },
    {
      imagePath: [
        OxfordShirtLightPink1,
        OxfordShirtLightPink2,
        OxfordShirtLightPink3,
      ],
      title: "Oxford Shirt",
      subtitle: "Regular Fit",
      description:
        "Elegant oxford shirt in light pink, perfect for a sophisticated and modern look.",
      price: "$22.99",
      gender: "Women",
      colors: ["Light Pink"],
    },
    {
      imagePath: [
        PopoverDenimShirtCream1,
        PopoverDenimShirtCream2,
        PopoverDenimShirtCream3,
      ],
      title: "Popover Denim Shirt",
      subtitle: "Regular Fit",
      description:
        "Stylish popover denim shirt, great for a casual and modern style.",
      price: "$19.99",
      gender: "Women",
      colors: ["Cream"],
    },
    {
      imagePath: [
        SequinedBlouseDarkGrey1,
        SequinedBlouseDarkGrey2,
        SequinedBlouseDarkGrey3,
      ],
      title: "Sequined Blouse",
      subtitle: "Regular Fit",
      description:
        "Elegant sequined blouse in dark grey, perfect for a sophisticated and stylish look.",
      price: "$20.49",
      gender: "Women",
      colors: ["Dark Grey"],
    },
  ],

  trousers: [
    {
      imagePath: [
        CigaretteTrousersBlack1,
        CigaretteTrousersBlack2,
        CigaretteTrousersBlack3,
      ],
      title: "Cigarette Trousers",
      subtitle: "Slim Fit",
      description:
        "Elegant cigarette trousers in black, perfect for a sophisticated and modern look.",
      price: "$24.99",
      gender: "Women",
      colors: ["Black"],
    },
    {
      imagePath: [
        FineKnitTrousersDarkBeige1,
        FineKnitTrousersDarkBeige2,
        FineKnitTrousersDarkBeige3,
      ],
      title: "Fine Knit Trousers",
      subtitle: "Regular Fit",
      description:
        "Comfortable fine knit trousers in dark beige, great for a relaxed and stylish look.",
      price: "$22.49",
      gender: "Women",
      colors: ["Dark Beige"],
    },
    {
      imagePath: [
        FlaredRibKnitTrousersBlack1,
        FlaredRibKnitTrousersBlack2,
        FlaredRibKnitTrousersBlack3,
      ],
      title: "Flared Rib Knit Trousers",
      subtitle: "Flared Fit",
      description:
        "Trendy flared rib knit trousers in black, perfect for a fashionable and unique style.",
      price: "$23.99",
      gender: "Women",
      colors: ["Black"],
    },
    {
      imagePath: [
        FlaredSportsLeggingsInDryMove1,
        FlaredSportsLeggingsInDryMove2,
        FlaredSportsLeggingsInDryMove3,
      ],
      title: "Flared Sports Leggings in DryMove",
      subtitle: "Flared Fit",
      description:
        "Comfortable flared sports leggings in DryMove fabric, ideal for active wear.",
      price: "$21.49",
      gender: "Women",
      colors: ["Black"],
    },
    {
      imagePath: [
        HighWaistedLeggingsBlack1,
        HighWaistedLeggingsBlack2,
        HighWaistedLeggingsBlack3,
      ],
      title: "High Waisted Leggings",
      subtitle: "Slim Fit",
      description:
        "Stylish high waisted leggings in black, perfect for a sleek and modern look.",
      price: "$19.99",
      gender: "Women",
      colors: ["Black"],
    },
    {
      imagePath: [SweatpantsBlack1, SweatpantsBlack2, SweatpantsBlack3],
      title: "Sweatpants",
      subtitle: "Regular Fit",
      description:
        "Comfortable sweatpants in black, great for a relaxed and casual style.",
      price: "$18.49",
      gender: "Women",
      colors: ["Black"],
    },
    {
      imagePath: [
        TailoredJerseyTrousersNavy1,
        TailoredJerseyTrousersNavy2,
        TailoredJerseyTrousersNavy3,
        TailoredJerseyTrousersNavy4,
      ],
      title: "Tailored Jersey Trousers",
      subtitle: "Regular Fit",
      description:
        "Elegant tailored jersey trousers in navy, perfect for a sophisticated look.",
      price: "$22.99",
      gender: "Women",
      colors: ["Navy"],
    },
    {
      imagePath: [
        WideJoggersPigeonBlue1,
        WideJoggersPigeonBlue2,
        WideJoggersPigeonBlue3,
      ],
      title: "Wide Joggers",
      subtitle: "Wide Fit",
      description:
        "Comfortable wide joggers in pigeon blue, great for a relaxed and stylish look.",
      price: "$20.49",
      gender: "Women",
      colors: ["Pigeon Blue"],
    },
    {
      imagePath: [
        WideTailoredTrousers1,
        WideTailoredTrousers2,
        WideTailoredTrousers3,
      ],
      title: "Wide Tailored Trousers",
      subtitle: "Wide Fit",
      description:
        "Elegant wide tailored trousers, perfect for a sophisticated and modern look.",
      price: "$23.49",
      gender: "Women",
      colors: ["Black"],
    },
    {
      imagePath: [
        WideTwillTrousersBlack1,
        WideTwillTrousersBlack2,
        WideTwillTrousersBlack3,
      ],
      title: "Wide Twill Trousers",
      subtitle: "Wide Fit",
      description:
        "Stylish wide twill trousers in black, great for a fashionable and unique style.",
      price: "$24.99",
      gender: "Women",
      colors: ["Black"],
    },
  ],
};
